""" Constants file """

# AWS
AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
S3_BUCKET = "S3_BUCKET"

# Table columns
TICKER = "TICKER"
DATE = "DATE"
OPEN = "OPEN"
CLOSE = "CLOSE"
HIGH = "HIGH"
LOW = "LOW"
VOLUME = "VOLUME"
RETURN = "RETURN"
AVERAGE_RETURN = "AVERAGE_RETURN"
STDDEV = "STANDARD_DEVIATION"
VALUE = "VALUE"

# Calculation related
TRADING_DAYS = 252
